### ISSUE TITLE
[Notificação] Análise

### ISSUE THREAD

**Issue by dsalexan** [UnifespCodeLab/plasmedis-api#13]
# Resumo
Verificar a plataforma e determinais quais funcionalidades devem enviar uma notificação ao usuário (novo comentário, nova postagem em categoria, novo usuário criado, etc...). Documentar a análise no seguinte modelo:

- Funcionalidade
- Tela
- "Perfil" de usuário envolvido (usuário comum, moderador, administrador)
  - Se você achar necessário criar um perfil de usuário novo por algum motivo, indicar também.
- Regime de notificação. Se deve ser notificado toda vez, somente a primeira vez, só se seguir a "coisa" (nem temos a funcionalidade de seguir, mas se achar que faz sentido uma issue pra criar a funcionalidade pode entrar na fila, etc...)
- Um rascunho (em texto mesmo) de como deveria ser a notificação.
  - ChatGPT existe

# Critérios de Aceite

- [x] /esqueci-minha-senha
  - Administrador deveria ser notificado quando um usuário envia requisição de esqueci minha senha? Ou talvez só indicaria em algum painel administrativo? Esse painel administrativo já existe ou tem que ser criado?
- _Essas paginas abaixo precisa estar logado_
- [x] /
- [x] /form
- [x] /complemento-de-dados
- [x] /register
- [x] /categorias
- [x] /admin/controle-de-usuarios

# Protótipo

# Informações Adicionais

- Essa tarefa vai exigir algum conhecimento de como a plataforma funciona, então você vai precisar executar o _plasmedis-web_ e sair fuçando.

**Comment by gacneves** [comment]
Criei um documento com algumas notificações que me veio a mente, se tiver alguma adição ou modificação, fiquem a vontade.

[Notificações - Plasmedis](https://docs.google.com/document/d/1wIa7PIufTpzZNOliSd3xsjw6hI6CiUQFTJNwNPsh7gw/edit?usp=sharing)

@dsalexan

**Comment by dsalexan** [comment]
Ta ok, vou adicionar no backlog os pontos em vermelho
