### ISSUE TITLE
[Paginação] Protótipo

### ISSUE THREAD

**Issue by dsalexan** [UnifespCodeLab/plasmedis-api#2]
# História de Usuário

O usuário quer retornar um número reduzido de entradas quando faz um requisição a um endpoint que retorna uma lista.

# Resumo

Criar um protótipo de paginação para retornar listas pela API. Inicialmente esse protótipo só precisa ser aplicado em um endpoint (GET users/, por exemplo).

A ideia é modificar o schema da resposta do endpoint para acomodar uma estrutura paginada e modificar o código do próprio endpoint para só retornar X resultados para uma determinada página Y.

As variaveis de paginação (número da pagina, quantidade de registros por página, etc...) devem ser informadas na query string da requisição.

# Critérios de Aceite

- [x] Modificar o schema do retorno endpoint
- [x] Modificar o retorno do endpoint
- [x] Modificar o código que o endpoint executa para acomodar paginação
- [x] Documentar o modelo de retorno paginado

# Protótipo

# Informações Adicionais

**Comment by gacneves** [comment]
Explicação do modelo de paginação

![prototipo_paginacao](https://user-images.githubusercontent.com/57917229/211331788-6f9d76ed-bff7-4016-abc8-c43613677c40.png)
