### ISSUE TITLE
[Notificações] Estudo de Caso

### ISSUE THREAD

**Issue by dsalexan** [UnifespCodeLab/plasmedis-api#3]
# História de Usuário

O usuário quer receber notificações sobre postagens relevantes.

# Resumo

O frontend deve ser capaz de pegar notificações coerentes com o usuário, como:

- Quando alguém faz uma postagem em uma categoria onde o usuário esta seguindo (ex. verificadas, postagens de moderador, categorias inscritas)
- Quando uma postagem do usuário é verificada
- Quando um moderador remove uma postagem de um usuário

A ideia é fazer um estudo de caso e criar um protótipo da estrutura de envio dessas notificações, dando uma ideia de como a **api** lidaria com o envio de notificação e do gerenciamento dessas notificações.

# Critérios de Aceite

- [x] Documento com o estudo de caso
  - [x] Como a api vai enviar as notificações
  - [x] Como detectar se o usuário leu a notificação
  - [x] Alguma estrutura dentro do banco vai ser necessária?

# Protótipo

# Informações Adicionais

Talvez tenha algo haver com PWA, apesar do front nao ser PWA

**Comment by gacneves** [comment]
### Possíveis Soluções

- Depois de algumas pesquisas, consigo listar 2 possíveis soluções para as notificações do sistema:
  - Controlado pelo backend: A API centralizaria tudo e gerenciaria as notificações. Cada notificação é armazenada em uma tabela no banco de dados, associada a um usuário específico.
    - Nessa opção teríamos o controle completo e será fácil de adaptar para o momento do projeto, sem a necessidade de integrar mais uma ferramenta, o que pode acarretar em custos (dependendo do uso, o free tier não sirva) e estudos da ferramenta.
    - A implementação pode ser complexa dependendo da customização de quisermos fazer dos usuários com as notificações.
    - Pensando em um número muito grande de usuários, essa solução se tornaria em um gargalo eventualmente.
  - Integrar com serviços externos: Aqui utilizamos serviços de notificações externos que servem como servidores para garantir a entrega das notificações em tempo real através de eventos ou ações específicas. FCM, RabbitMQ, OneSignal, são exemplos de algumas ferramentas.
    - Esta opção pode ser mais simples de se implementar porém se faz necessário o conhecimento de tais ferramentas.
    - A escalabilidade é simples, permitindo atender muitos usuários simultaneamente.
    - Utilização de ferramentas externas devem gerar custos, além de ficarmos limitados as funções que os softwares disponibilizam.

Dito isso, acredito que seguiremos a primeira, mas gostaria de ouvir de vocês. Em minha opinião a primeira solução é a melhor escolha no momento, acho que é uma oportunidade boa de desenvolvimento e eu ficaria feliz em contribuir.

 ### Arquitetura proposta

Baseando-se na primeira solução, vejo algumas necessidades:
- Tabela Notifications com os campos requisitos ID, ID do usuário, conteúdo (texto) e se ja foi lida (boleano).
- Tabela User Preferences ou algum campo na tabela Users (opcional) para personalização das notificações.
- Endpoints na API:
  - POST /notifications: usado para criar notificações quando uma ação que precisa notificar o usuário for tomada (precisa do conteúdo e usuário a ser notificado)
  - GET /notifications: lista todas notificações
  - GET /notifications/user/<int:id>: retorna as notificações do usuário com id passado.
  - PUT/PATCH /notifications/<int:id>:  marca notificação como lida
- Adições no front:
  - Área de visualização das notificações (Facebook-like é uma opção)
    - Mostrar todas as notificações (?)
    - Destacar não lidas
    - Botão de marcar como lida (apenas uma, ou todas não lidas)
  - Periodicamente buscar as notificações do usuário
    - Pequeno pop-up de novas notificações (?)
 
PS: Acredito que a questão do PWA está um pouco fora do nosso alcance no momento. Como temos um aplicativo web, notificações simples (como as de celulares) são um pouco mais difíceis de serem implementadas (não sei exatamente como seria feito), porém podemos pensar em talvez enviar emails. Contendo um resumo de notificações caso o usuário não leia elas no aplicativo, o que acham? (Por isso a personalização das notificações por usuário, para controlar o envio de emails, se quer ou não, etc).

**Comment by gacneves** [comment]
@dsalexan Estou a disposição se precisar esclarecer algo, ou se quiser discutir mais sobre a proposta. Aparecerei na reunião hoje.
