### ISSUE TITLE
[Gerenciamento de Postagem] Remover Postagem

### ISSUE THREAD

**Issue by Maegima** [UnifespCodeLab/plasmedis-api#8]
# História de Usuário
- O usuário deve ser capaz de excluir suas postagens.
- Um moderador/administrador deve ser capaz de excluir quaisquer postagens.

# Resumo

> **DELETE** /postagens/<postagem_id>

Criar a rota acima para remover postagens e seus comentários. Essa rota deve verificar se o usuário autenticado é o criador da postagem **ou** é um administrador/moderador.

# Critérios de Aceite
- [ ] Criar rota para remover postagens.
- [ ] Verificar se o usuário é o criador **ou** administrador/moderador
- [ ] Comentários de postagens também devem ser removidos.

# Protótipo
----

# Informações Adicionais
Um Guia para verificação do usuário autenticado pode ser encontrado no notion em [PlaSMeDIS > Guias de Uso > [API] Usuário Autenticado](https://www.notion.so/API-Usu-rio-Autenticado-193c8d8b0dd44c2c940616d4b15ab5a6)

**Comment by dsalexan** [comment]
@raissabarb dei uma atualizada na descrição da task, incluindo o guia para verificar o usuário autenticado que mencionei no slack
